# Generated by Django 3.2.2 on 2021-05-12 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 22, 21, 49, 452796, tzinfo=utc), editable=False),
        ),
    ]
