# Generated by Django 3.2.2 on 2021-05-12 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
