# Generated by Django 3.2.2 on 2021-05-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name_plural': 'Especialidades'},
        ),
    ]
