# Generated by Django 3.2.2 on 2021-05-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_especialidades_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
