# Generated by Django 3.2.2 on 2021-05-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_alter_especialidades_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidade',
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={},
        ),
    ]
