# Generated by Django 3.2.2 on 2021-05-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='agendas.agenda'),
        ),
    ]
