# Generated by Django 3.2.2 on 2021-05-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_alter_hora_agenda'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agenda',
            managers=[
            ],
        ),
    ]
