# Generated by Django 3.2.2 on 2021-05-07 04:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_alter_agenda_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agenda',
            managers=[
                ('disponivel', django.db.models.manager.Manager()),
            ],
        ),
    ]
