# Generated by Django 3.2.2 on 2021-05-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_rename_hora_horarioagenda'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agenda',
            managers=[
            ],
        ),
    ]
